export async function sendOtpDevSms(phoneNumber: string, otpCode: string) {
  const apiKey = process.env.OTP_DEV_API_KEY;
  const templateId = process.env.OTP_DEV_TEMPLATE_ID;
  const sender = process.env.OTP_DEV_SENDER || 'OTP Dev';

  if (!apiKey || !templateId) {
    throw new Error('OTP.dev credentials missing in environment variables');
  }

  // Format phone to 91XXXXXXXXXX (Indian format without + or spaces)
  const cleanPhone = phoneNumber.replace(/[^0-9]/g, '');
  const formattedPhone = cleanPhone.startsWith('91') && cleanPhone.length === 12
    ? cleanPhone
    : `91${cleanPhone.slice(-10)}`;

  const response = await fetch('https://api.otp.dev/v1/verifications', {
    method: 'POST',
    headers: {
      'X-OTP-Key': apiKey,
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      data: {
        channel: 'sms',
        sender: sender,
        phone: formattedPhone,
        template: templateId,
        code: otpCode, // Send the 6-digit code generated by our server
      },
    }),
  });

  const data = await response.json();
  if (!response.ok) {
    const errorMsg = data.errors?.[0]?.message || data.message || 'Failed to send SMS';
    throw new Error(errorMsg);
  }

  return data;
}
